create table cidade (id bigint not null auto_increment, nome varchar(255) not null, estado_id bigint not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, ativo bit not null, descricao varchar(255) not null, nome varchar(255) not null, preco decimal(19,2) not null, restaurante_id bigint not null, primary key (id)) engine=InnoDB;
create table restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
insert into cozinha (id, nome) values (1, 'Tailandesa');
insert into cozinha (id, nome) values (2, 'Italiana');
insert into cozinha (id, nome) values (3, 'Brasileira');
insert into cozinha (id, nome) values (4, 'Mexicana');
insert into cozinha (id, nome) values (5, 'Japonesa');
insert into estado (id, nome) values (1, 'Paraná');
insert into estado (id, nome) values (2, 'Santa Catarina');
insert into estado (id, nome) values (3, 'Minas Gerais');
insert into cidade (id, nome, estado_id) values (1, 'Curitiba', 1);
insert into cidade (id, nome, estado_id) values (2, 'Florianópolis', 2);
insert into cidade (id, nome, estado_id) values (3, 'Belo Horizonte', 3);
insert into restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro, data_cadastro, data_atualizacao) values ('Xing Ling', 10, 1,1, 86000-000, 'Rua das Flores', '500', 'Centro', utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Madre Mio Delivery', 9.50, 2, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Cantina da Vovó', 3.90, 3, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Bar do Tadeu', 2.10, 3, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Muchachados Taqueria', 8, 4, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values('Dachô', 11, 5, utc_timestamp, utc_timestamp);
insert into forma_pagamento (id, descricao) values (1, 'pix');
insert into forma_pagamento (id, descricao) values (2, 'cartao de credito');
insert into forma_pagamento (id, descricao) values (3, 'boleto');
insert into permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3), (4, 1), (4, 2),(5, 1), (5, 3), (6, 1), (6, 2), (6, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Pad Thai', 'Tradicional macarrao frito Tailandes', 25.00, 1, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Bistecca alla Fiorentina', 'Suculento bife grande de bisteca (T-bone), de 4 a 6 cm de altura, grelhado', 80, 1, 2);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Porçao de frango','500g de frango à passarinho frito no capricho',21, 1, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Taco Tradicional','com a tortilha de milho em forma de disco',25, 1, 5);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Prato do dia','Comidinha caseira com tempero de avó, você só encontra aqui.', 39.90, 1,3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Temaki', 'Enrolado de alga em forma de cone recheado com arroz, salmão, cream cheese e cebolinha.', 18, 1, 6);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Peixe frito','Deliciosas iscas de tilápia frita na hora',5,1,4);
create table cidade (id bigint not null auto_increment, nome varchar(255) not null, estado_id bigint not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, ativo bit not null, descricao varchar(255) not null, nome varchar(255) not null, preco decimal(19,2) not null, restaurante_id bigint not null, primary key (id)) engine=InnoDB;
create table restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
insert into cozinha (id, nome) values (1, 'Tailandesa');
insert into cozinha (id, nome) values (2, 'Italiana');
insert into cozinha (id, nome) values (3, 'Brasileira');
insert into cozinha (id, nome) values (4, 'Mexicana');
insert into cozinha (id, nome) values (5, 'Japonesa');
insert into estado (id, nome) values (1, 'Paraná');
insert into estado (id, nome) values (2, 'Santa Catarina');
insert into estado (id, nome) values (3, 'Minas Gerais');
insert into cidade (id, nome, estado_id) values (1, 'Curitiba', 1);
insert into cidade (id, nome, estado_id) values (2, 'Florianópolis', 2);
insert into cidade (id, nome, estado_id) values (3, 'Belo Horizonte', 3);
insert into restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro, data_cadastro, data_atualizacao) values ('Xing Ling', 10, 1,1, 86000-000, 'Rua das Flores', '500', 'Centro', utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Madre Mio Delivery', 9.50, 2, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Cantina da Vovó', 3.90, 3, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Bar do Tadeu', 2.10, 3, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Muchachados Taqueria', 8, 4, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values('Dachô', 11, 5, utc_timestamp, utc_timestamp);
insert into forma_pagamento (id, descricao) values (1, 'pix');
insert into forma_pagamento (id, descricao) values (2, 'cartao de credito');
insert into forma_pagamento (id, descricao) values (3, 'boleto');
insert into permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3), (4, 1), (4, 2),(5, 1), (5, 3), (6, 1), (6, 2), (6, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Pad Thai', 'Tradicional macarrao frito Tailandes', 25.00, 1, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Bistecca alla Fiorentina', 'Suculento bife grande de bisteca (T-bone), de 4 a 6 cm de altura, grelhado', 80, 1, 2);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Porçao de frango','500g de frango à passarinho frito no capricho',21, 1, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Taco Tradicional','com a tortilha de milho em forma de disco',25, 1, 5);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Prato do dia','Comidinha caseira com tempero de avó, você só encontra aqui.', 39.90, 1,3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Temaki', 'Enrolado de alga em forma de cone recheado com arroz, salmão, cream cheese e cebolinha.', 18, 1, 6);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Peixe frito','Deliciosas iscas de tilápia frita na hora',5,1,4);
create table cidade (id bigint not null auto_increment, nome varchar(255) not null, estado_id bigint not null, primary key (id)) engine=InnoDB;
create table cozinha (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table estado (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table forma_pagamento (id bigint not null auto_increment, descricao varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo (id bigint not null auto_increment, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table grupo_permissao (grupo_id bigint not null, permissao_id bigint not null) engine=InnoDB;
create table permissao (id bigint not null auto_increment, descricao varchar(255) not null, nome varchar(255) not null, primary key (id)) engine=InnoDB;
create table produto (id bigint not null auto_increment, ativo bit not null, descricao varchar(255) not null, nome varchar(255) not null, preco decimal(19,2) not null, restaurante_id bigint not null, primary key (id)) engine=InnoDB;
create table restaurante (id bigint not null auto_increment, data_atualizacao datetime not null, data_cadastro datetime not null, endereco_bairro varchar(255), endereco_cep varchar(255), endereco_complemento varchar(255), endereco_logradouro varchar(255), endereco_numero varchar(255), nome varchar(255) not null, taxa_frete decimal(19,2) not null, cozinha_id bigint not null, endereco_cidade_id bigint, primary key (id)) engine=InnoDB;
create table restaurante_forma_pagamento (restaurante_id bigint not null, forma_pagamento_id bigint not null) engine=InnoDB;
create table usuario (id bigint not null auto_increment, data_cadastro datetime not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id)) engine=InnoDB;
create table usuario_grupo (usuario_id bigint not null, grupo_id bigint not null) engine=InnoDB;
alter table cidade add constraint FKkworrwk40xj58kevvh3evi500 foreign key (estado_id) references estado (id);
alter table grupo_permissao add constraint FKh21kiw0y0hxg6birmdf2ef6vy foreign key (permissao_id) references permissao (id);
alter table grupo_permissao add constraint FKta4si8vh3f4jo3bsslvkscc2m foreign key (grupo_id) references grupo (id);
alter table produto add constraint FKb9jhjyghjcn25guim7q4pt8qx foreign key (restaurante_id) references restaurante (id);
alter table restaurante add constraint FK76grk4roudh659skcgbnanthi foreign key (cozinha_id) references cozinha (id);
alter table restaurante add constraint FKbc0tm7hnvc96d8e7e2ulb05yw foreign key (endereco_cidade_id) references cidade (id);
alter table restaurante_forma_pagamento add constraint FK7aln770m80358y4olr03hyhh2 foreign key (forma_pagamento_id) references forma_pagamento (id);
alter table restaurante_forma_pagamento add constraint FKa30vowfejemkw7whjvr8pryvj foreign key (restaurante_id) references restaurante (id);
alter table usuario_grupo add constraint FKk30suuy31cq5u36m9am4om9ju foreign key (grupo_id) references grupo (id);
alter table usuario_grupo add constraint FKdofo9es0esuiahyw2q467crxw foreign key (usuario_id) references usuario (id);
insert into cozinha (id, nome) values (1, 'Tailandesa');
insert into cozinha (id, nome) values (2, 'Italiana');
insert into cozinha (id, nome) values (3, 'Brasileira');
insert into cozinha (id, nome) values (4, 'Mexicana');
insert into cozinha (id, nome) values (5, 'Japonesa');
insert into estado (id, nome) values (1, 'Paraná');
insert into estado (id, nome) values (2, 'Santa Catarina');
insert into estado (id, nome) values (3, 'Minas Gerais');
insert into cidade (id, nome, estado_id) values (1, 'Curitiba', 1);
insert into cidade (id, nome, estado_id) values (2, 'Florianópolis', 2);
insert into cidade (id, nome, estado_id) values (3, 'Belo Horizonte', 3);
insert into restaurante (nome, taxa_frete, cozinha_id, endereco_cidade_id, endereco_cep, endereco_logradouro, endereco_numero, endereco_bairro, data_cadastro, data_atualizacao) values ('Xing Ling', 10, 1,1, 86000-000, 'Rua das Flores', '500', 'Centro', utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Madre Mio Delivery', 9.50, 2, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Cantina da Vovó', 3.90, 3, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Bar do Tadeu', 2.10, 3, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values ('Muchachados Taqueria', 8, 4, utc_timestamp, utc_timestamp);
insert into restaurante (nome, taxa_frete, cozinha_id, data_cadastro, data_atualizacao) values('Dachô', 11, 5, utc_timestamp, utc_timestamp);
insert into forma_pagamento (id, descricao) values (1, 'pix');
insert into forma_pagamento (id, descricao) values (2, 'cartao de credito');
insert into forma_pagamento (id, descricao) values (3, 'boleto');
insert into permissao (id, nome, descricao) values (1, 'CONSULTAR_COZINHAS', 'Permite consultar cozinhas');
insert into permissao (id, nome, descricao) values (2, 'EDITAR_COZINHAS', 'Permite editar cozinhas');
insert into restaurante_forma_pagamento (restaurante_id, forma_pagamento_id) values (1, 1), (1, 2), (1, 3), (2, 3), (3, 2), (3, 3), (4, 1), (4, 2),(5, 1), (5, 3), (6, 1), (6, 2), (6, 3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Pad Thai', 'Tradicional macarrao frito Tailandes', 25.00, 1, 1);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Bistecca alla Fiorentina', 'Suculento bife grande de bisteca (T-bone), de 4 a 6 cm de altura, grelhado', 80, 1, 2);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Porçao de frango','500g de frango à passarinho frito no capricho',21, 1, 4);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Taco Tradicional','com a tortilha de milho em forma de disco',25, 1, 5);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Prato do dia','Comidinha caseira com tempero de avó, você só encontra aqui.', 39.90, 1,3);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Temaki', 'Enrolado de alga em forma de cone recheado com arroz, salmão, cream cheese e cebolinha.', 18, 1, 6);
insert into produto (nome, descricao, preco, ativo, restaurante_id) values ('Peixe frito','Deliciosas iscas de tilápia frita na hora',5,1,4);
